version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    env_file:
      - db.env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'; env"
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file:
      - app.env
volumes:
  mysql-data: