version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0

workflows:
  rails-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: ./
          region: AWS_REGION
          repo: 'mogstagram-rails'
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
        requires:
          - aws-ecr/build-and-push-image
        family: 'mogstagram-task'
        cluster-name: 'mogstagram-cluster'
        service-name: 'mogstagram-service'
        container-image-name-updates: 'container=rails,image-and-tag=${AWS_ECR_ACCOUNT_URL}/mogstagram-rails:${CIRCLE_SHA1}'